sudo: required

language: generic

services:
  - docker

before_install:
  - docker pull grburgess/3ml-science:finished
  - docker run grburgess/3ml-science:finished /bin/sh -c 'cd /root/polarpy && ls'
