sudo: required

language: generic

services:
  - docker

before_install:
  - |2
    docker pull grburgess/3ml-science:finished

script:
  - |2

    docker run -e TRAVIS_BUILD_DIR \
               -e TRAVIS_PYTHON_VERSION=2.7 \
               -e TRAVIS_BRANCH \
               -e TRAVIS_BUILD_NUMBER \
               -e TRAVIS_EVENT_TYPE \
               -v ${TRAVIS_BUILD_DIR}:${TRAVIS_BUILD_DIR} \
               -it grburgess/3ml-science:finished /bin/bash -c 'source ${TRAVIS_BUILD_DIR}/ci/test.sh'

