sudo: required

language: generic

services:
  - docker

before_install:
  - docker pull grburgess/polar:finished

script:
  - docker run -e TRAVIS_BUILD_DIR\
  -it grburgess/polar:finished\
  /bin/sh -c 'source ${TRAVIS_BUILD_DIR}/ci/test.sh'
